#!/bin/bash

# Get the filename without the extension
filename="${CFILE%.*}"

# Compile the C file with -S flag to generate assembly code
gcc -S -masm=intel "$CFILE"

# Rename the output file to have .s extension
mv "${filename}.s" "${filename}.s"
